<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-2336HU1" failures="4" tests="10" name="Package level Test" time="120.419" errors="0" timestamp="2023-02-17T23:50:01 TRT">
  <testcase classname="com.exelenter.class02._01_ValidationTests" name="titleValidation" time="0.005"/>
  <testcase classname="com.exelenter.class02._01_ValidationTests" name="logoValidation" time="0.044"/>
  <testcase classname="com.exelenter.class02._01_ValidationTests" name="validLoginTest" time="7.415"/>
  <testcase classname="com.exelenter.class02._02_AssertDemo" name="validLoginTest" time="1.848"/>
  <testcase classname="com.exelenter.class02._02_AssertDemo" name="invalidLoginTest" time="0.319">
    <failure type="java.lang.AssertionError" message="Message Error is incorrect. expected [Password cannot be empty1] but found [Password cannot be empty]">
      <![CDATA[java.lang.AssertionError: Message Error is incorrect. expected [Password cannot be empty1] but found [Password cannot be empty]
at com.exelenter.class02._02_AssertDemo.invalidLoginTest(_02_AssertDemo.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- invalidLoginTest -->
  <testcase classname="com.exelenter.class03._01_SoftAssertRecap" name="testCase" time="0.0">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at com.exelenter.class03._01_SoftAssertRecap.testCase(_01_SoftAssertRecap.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
  <testcase classname="com.exelenter.class02._03_TitleAndLogoValidation" name="titleValidation" time="0.006">
    <failure type="java.lang.AssertionError" message="Title does not match! expected [Exelenter Project!!!] but found [Exelenter Project]">
      <![CDATA[java.lang.AssertionError: Title does not match! expected [Exelenter Project!!!] but found [Exelenter Project]
at com.exelenter.class02._03_TitleAndLogoValidation.titleValidation(_03_TitleAndLogoValidation.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- titleValidation -->
  <testcase classname="com.exelenter.class02._03_TitleAndLogoValidation" name="logoValidation" time="0.0">
    <skipped/>
  </testcase> <!-- logoValidation -->
  <testcase classname="com.exelenter.class02._04_Task1" name="dashboardLogoValidation" time="2.4"/>
  <testcase classname="com.exelenter.class02._05_SoftAssertDemo" name="softAssertionTest" time="10.493">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Login logo is not displayed. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Login logo is not displayed. expected [true] but found [false]
at com.exelenter.class02._05_SoftAssertDemo.softAssertionTest(_05_SoftAssertDemo.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- softAssertionTest -->
</testsuite> <!-- Package level Test -->
